# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-18 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20161107_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='doctors',
        ),
        migrations.AddField(
            model_name='registration',
            name='employed_hospitals',
            field=models.ManyToManyField(related_name='doctors', to='system.Hospital'),
        ),
    ]
