# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20161204_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='patient_readable',
            field=models.BooleanField(default=False),
        ),
    ]
